### ISSUE TITLE
Доработки и добавление одного и более автора

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/bibliography#19]
Проект немного переработан. Проведен рефакторинг. Внимательнее относитесь к тому что делаете.

1. Сделать кнопку скрыть/показать доступную в режиме редактирования с иконкой "глаз" el-icon-view. Если кнопка прожата, то источник отображается при обычном просмотре, если отключена, то не показывается. В режиме редактирования источник видно всегда.

2. Добавить возможность добавления нескольких авторов. Информацию об авторах вынести в поле authors (массив). Сделать отдельную форму автора, которая интегрируется внутрь формы источника. В форме книги, должна быть кнопка добавить автора, что увеличивает массив и добавляет для просмотра новую форму автора для редактирования.

**Comment by AndrewVorotyntsev** [comment]
Я хотел бы уточнить по первому пункту. У нас есть кнопка выбора источника на главном экране (` / `). На экране редактирования списка (`/edit`) нужно добавить кнопку с глазом. По умолчанию она включена и кнопка выбора источника на главном экране отображается. По нажатию кнопка на главном экране скрывается. Кнопку выбора источника на экране редактирования (`/edit/:id`) это никак не затрагивает.

**Comment by AndrewVorotyntsev** [comment]
А что-то не пойму, что значит "источник" в первом пункте?

**Comment by reznikovkg** [comment]
Источник - литература - книга - это все одно и тоже понятие. Кнопка должна работать как переключатель вкл/выкл.
